// Swift File generated by the BNF Converter (bnfc 2.9.6).

import Antlr4

public func ast(from text: String) -> Result<Program, Error> {
  let input = ANTLRInputStream(text)
  let lexer = StellaLexer(input)
  let tokens = CommonTokenStream(lexer)
  do {
    let parser = try StellaParser(tokens)
    let ctx = try parser.program()
    let program = try buildProgram(ctx)
    return .success(program)
  } catch {
    return .failure(error)
  }
}
