## File generated by the BNF Converter (bnfc 2.9.6).

LANG=Stella
LEXER_NAME=StellaLexer
PARSER_NAME=StellaParser
ANTLR4=antlr4

.PHONY : all clean remove

all : ${LANG}

lexer : Stella/Sources/Stella/${LEXER_NAME}.g4
	${ANTLR4} -Dlanguage=Swift Stella/Sources/Stella/${LEXER_NAME}.g4

parser : Stella/Sources/Stella/${PARSER_NAME}.g4
	${ANTLR4} -Dlanguage=Swift -no-listener -no-visitor Stella/Sources/Stella/${PARSER_NAME}.g4

${LANG} : lexer parser clean

clean :
	rm -f Stella/Sources/Stella/${LEXER_NAME}.interp
	rm -f Stella/Sources/Stella/${LEXER_NAME}.tokens
	rm -f Stella/Sources/Stella/${PARSER_NAME}.interp
	rm -f Stella/Sources/Stella/${PARSER_NAME}.tokens
	rm -f Stella/Sources/Stella/${LEXER_NAME}.g4
	rm -f Stella/Sources/Stella/${PARSER_NAME}.g4

remove :
	rm -rf ${LANG}

