// swift-tools-version: 5.9
// Swift File generated by the BNF Converter (bnfc 2.9.6).

import PackageDescription

let package = Package(
  name: "Stella",
  products: [
    .library(
      name: "Stella",
      targets: ["Stella"]
    )
  ],
  dependencies: [
    .package(name: "Antlr4", url: "https://github.com/antlr/antlr4", from: "4.12.0")
  ],
  targets: [
    .target(name: "Stella", dependencies: ["Antlr4"])
  ]
)
